version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:7.6.0
    environment:
    # - bootstrap.memory_lock=true
    - cluster.name=docker-cluster
    - discovery.type=single-node
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
    - "9200:9200"
    volumes:
    - ./data-elasticsearch:/usr/share/elasticsearch/data
    restart: always

  kibana:
    image: kibana:7.6.0
    restart: always

    ports:
    - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      xpack.monitoring.ui.container.elasticsearch.enabled: "false"
